/*-----------------------------------------------------------------------------
   Copyright(c) Tellabs Transport Group Inc. All rights reserved.

SUBSYSTEM:      Software Services
TARGET:          
AUTHOR:         March 28, 2003- Jean-Francois Tremblay
DESCRIPTION:    Header file for TL1 Notification Observer If declaration
-----------------------------------------------------------------------------*/ 
#ifdef WIN32 // Microsoft bug, identifier that exceeds 255 chars gets truncated
    #pragma warning(disable:4786)
#endif

#ifndef __TL1_NOTIFICATION_H__
#define __TL1_NOTIFICATION_H__

#include <gdef.h>

class TL1_GeneralRspBlk;
class TL1_Response;

class TL1_Notification
{
public:
    enum TL1_NotifType {
        UNKNOWN,
        ED_CRS,
        DLT_CRS,
        ED_TIDIPMAP,
        DLT_TIDIPMAP,
        ED_NEIDMAP,
        DLT_NEIDMAP,
        ENT_NEIDMAP,
        ED_NET,
        ED_IF_ROUTER,
        ED_NTPPEER,
        DLT_NTPPEER,
        ED_ALMPF,
        ED_DHCP,
        SET_TH,
        SET_PMMODE,
        SET_TCAMODE,
        SET_PMDAY,
        SCHED_PMREPT,
        SCHED_PMFILE,
        ED_FTPSERVER,
        DLT_FTPSERVER,
        ED_INV,
        DLT_INV,
        ED_EQPT,
        DLT_EQPT,
        ED_SLOT,
        DLT_SLOT,
        ED_OC3,
        DLT_OC3,
        ED_OC12,
        DLT_OC12,
        ED_OC48,
        DLT_OC48,
        ED_OC192,
        DLT_OC192,
        ED_OC768,
        DLT_OC768,
        ED_STM1,
        DLT_STM1,
        ED_STM4,
        DLT_STM4,
        ED_STM16,
        DLT_STM16,
        ED_STM64,
        DLT_STM64,
        ED_STM256,
        DLT_STM256,
        ED_GBEP,
        DLT_GBEP,
        ED_GOPT,
        DLT_GOPT,
        ED_GOPTM,
        DLT_GOPTM,
        ED_TGBEP,
        DLT_TGBEP,
        ED_OCH,
        DLT_OCH,
        ED_OTS,
        DLT_OTS,
        ED_OSC,
        DLT_OSC,
        ED_OSCX,
        DLT_OSCX,
        ED_OMS,
        DLT_OMS,        
        ED_OPTD,
        DLT_OPTD,
        SET_OPTPWR,
        SET_GAIN,
        SET_ATTN_OCH,
        SET_ATTN_OMS,
        ED_USER_SECU,
        DLT_USER_SECU,
        ED_SYS_SECU,
        ED_RADSERVER,
        DLT_RADSERVER,
        ED_DB,
        SCHED_BKUP_MEM,
        OPR_EXT_CONT,
        SET_ATTR_ENV,
        ED_ROUTER,
        ED_T1,
        DLT_T1,
        ED_E1,
        DLT_E1,
        ED_FFP,
        DLT_FFP,
        ED_SYNC,
        DLT_SYNC,
        ED_STS1,
        DLT_STS1,
        ED_STS3C,
        DLT_STS3C,
        ED_STS12C,
        DLT_STS12C,
        ED_STS48C,
        DLT_STS48C,
        ED_STS192C,
        DLT_STS192C,
        ED_STS3T,
        DLT_STS3T,
        ED_STS12T,
        DLT_STS12T,
        ED_STS48T,
        DLT_STS48T,
        ED_STS192T,
        DLT_STS192T,
        ED_STS1C22V,
        DLT_STS1C22V,
        ED_STS1CNV,
        DLT_STS1CNV,
        ED_STS3CNV,
        DLT_STS3CNV,
        ED_GOPTW,
        DLT_GOPTW,
        ED_GOPTP,
        DLT_GOPTP,
        ED_GFP,
        DLT_GFP,
        ED_OC3M,
        DLT_OC3M,
        ED_OC12M,
        DLT_OC12M,
        ED_OC48M,
        DLT_OC48M,
        ED_FIBR,
        DLT_FIBR,
        ED_TGLAN,
        DLT_TGLAN,
        ED_WARNING,
        ED_LEDS,
        ED_SNMP,
        ED_CNAMETIDMAP,
        DLT_CNAMETIDMAP,
        ED_SNMP_COMMPREFIX,
        DLT_SNMP_COMMPREFIX,
        ED_ODU0,
        DLT_ODU0,
        ED_ODU0TA,
        DLT_ODU0TA,
        ED_ODU0TB,     
        DLT_ODU0TB,
        ED_ODU1,
        DLT_ODU1,
        ED_ODU1TA,
        DLT_ODU1TA,
        ED_ODU1TB,     
        DLT_ODU1TB,       
        ED_ODU2,
        DLT_ODU2,
        ED_ODU2E,
        DLT_ODU2E,
        ED_ODU2TA,
        DLT_ODU2TA,
        ED_ODU2TB,     
        DLT_ODU2TB,
        ED_ODU3,
        DLT_ODU3,
        ED_ODU4,
        DLT_ODU4,
        ED_ODU3TA,
        DLT_ODU3TA,
        ED_ODU3TB,     
        DLT_ODU3TB,       
        ED_ODU4TA,
        DLT_ODU4TA,
        ED_ODUF,
        DLT_ODUF,
        ED_OTU1,
        DLT_OTU1,
        ED_OTU2,
        DLT_OTU2,
        ED_OTU3,
        DLT_OTU3,
        ED_OTU4,
        DLT_OTU4,
        ED_TGFC,
        DLT_TGFC,
        ED_FC8G,
        DLT_FC8G,
        ED_HGE,
        DLT_HGE,
        ED_FGE,
        DLT_FGE,
        ED_IPSEC,
        DLT_IPSEC,
        ED_LAPDPF,
        ED_LAPD,
        DLT_LAPD,
        ED_PPPPF,
        ED_PPP,
        DLT_PPP,
        ED_GCC,
        DLT_GCC,	
        ED_NP,
        DLT_NP,
        ED_STAT_RTE,
        DLT_STAT_RTE,
        ED_RSVP,
        DLT_RSVP,
        ED_RSVPADJ,
        DLT_RSVPADJ,
        ED_CALL,
        DLT_CALL,
        ED_CONN,
        DLT_CONN,
        ED_NODE,
        DLT_NODE,
        ED_CPPF,
        ED_TL,
        DLT_TL,
        ED_BL,
        ED_BL_MEMBER,
        DLT_BL,
        ED_TNALNKMAP,
        DLT_TNALNKMAP,
        ED_LINKPF,
        ED_SLPF,
        ED_SLPOLICY,
        ED_OSIRTR,
        DLT_OSIRTR,
        ED_OSPF,
        DLT_OSPF,
        ED_OSPFADJ,
        DLT_OSPFADJ,
        ED_OSPFAREA,
        DLT_OSPFAREA,
        ED_OSPFRP,
        DLT_OSPFRP,
        ED_OSPFRPMAP,
        DLT_OSPFRPMAP,
        ED_PSK,
        DLT_PSK,
        ED_CERT,
        DLT_CERT,
        ED_TARP,
        DLT_TARP,
        ED_TAP,
        DLT_TAP,
        ED_TACC,
        CHG_TACC,
        DISC_TACC,
        ED_VC3,
        DLT_VC3,
        ED_VC4,
        DLT_VC4,
        ED_VC44C,
        DLT_VC44C,
        ED_VC416C,
        DLT_VC416C,
        ED_VC464C,
        DLT_VC464C,
        ED_STM1T,
        DLT_STM1T,
        ED_STM4T,
        DLT_STM4T,
        ED_STM16T,
        DLT_STM16T,
        ED_STM64T,
        DLT_STM64T,
        ED_VC3NV,
        DLT_VC3NV,
        ED_VC4NV,
        DLT_VC4NV,
        ED_ENGIDMAP,
        DLT_ENGIDMAP,
        ED_TRAPIP,
        DLT_TRAPIP,
        ED_PPG,
        DLT_PPG,
        ED_NE,
        ED_EVC,
        DLT_EVC,
        ED_VCG,
        DLT_VCG,
        ED_LAG,
        DLT_LAG,
        ED_ETH,
        DLT_ETH,
        ED_TTP,
        DLT_TTP,
        ED_BWPF,
        DLT_BWPF,
        ED_SWITCHDOMAIN,
        DLT_SWITCHDOMAIN,
        ED_PMPF,
        ED_CFPF,
        ED_PMPF_USER,
        ED_EXPPATH,
        DLT_EXPPATH,
		ED_SYNCETH,
        DLT_SYNCETH,
        ED_TRL,
        DLT_TRL,
        ED_LABELSET,
        DLT_LABELSET,
        ED_SPD,
        DLT_SPD,
        ED_NETIFCONFIG,
        DLT_NETIFCONFIG,
        ED_TCPIP,
        ED_DA,
        DLT_DA,
        ED_ODUFTA,
        DLT_ODUFTA,
        ED_ODUFTB,     
        DLT_ODUFTB,
        ED_SWVER,
        ED_FPGAVER,
        ED_MGTETH,
        DLT_MGTETH,
        ED_MTERA,
        ED_WCG,
        DLT_WCG,
        ED_PROXY,
        ED_EXDPATH,
        DLT_EXDPATH,
        ED_SW,
        ED_DCNETHPORT,
        ED_AAA,
        DLT_AAA,
        ALL_NOTIF,
#ifdef PICO		
        ED_IPPG,
        DLT_IPPG,		
#endif		
// Additions for DB notifications should be made above ALL_NOTIF.                    //
// All other should be made at the end of the list                               //
// Any changes above this comment REQUIRE a change to T7100_TL1Dbchg_Helper.cpp //
// and MAY REQUIRE a change to T7100_TL1DBChangeSnapshot.h, .cpp, and  //
//.T7100_TL1SnapshotFormattingLogic.cpp //

// Whenever a new value is added to TL1Notification, the tables in //
// TL1Services/TL1DbChg/T7100_TL1SnapshotFormattingLogic.cpp and //
// TL1Services/TL1DbChg/T7100_TL1DbChgSnapshot.cpp //
// must be updated to include the new TL1Notification type by adding a new row to the tables //
// in exactly the same position as the new TL1Notification type.//

        RMV,
        RST,
        ALM,
        ALMENV,
        EVT,
        EVT_TCA,
        PM,
        BCKUP,
        FXFR,
        EVT_FFP,
        EVT_SESSION
    };

    TL1_Notification( TL1_NotifType theType, const TL1_Response& theResponse );

    virtual ~TL1_Notification();

    TL1_NotifType GetType() const { return itsType; }

    uint32 GetAtag() const { return itsAtag; }

    const TL1_Response& GetResponse() const;

private:

    TL1_NotifType itsType;
    uint32 itsAtag;
    const TL1_Response& itsResponse;
};

#endif


